### ISSUE TITLE
Authenticating XPC connections

### ISSUE THREAD

**Issue by jeff-h** [shpakovski/SwiftXPC#1]
This looks great! Thanks for sharing it.

I am wondering whether you have considered the need for security when accepting XPC connections. If not, I'm keen to see such an implementation in a fresh codebase from someone way more experienced than me :)

Background:

* https://blog.obdev.at/what-we-have-learned-from-a-vulnerability/
* https://mjtsai.com/blog/2019/09/02/privilegedhelpertools-and-checking-xpc-peers/
* https://theevilbit.github.io/posts/secure_coding_privilegedhelpertools_part1/

**Comment by shpakovski** [comment]
Hey Jeff, thanks a lot for the kind words! It’s great that you found the sample project useful 👍

I heard about the described problem, and it’s nice that you provided some links to quickly refresh memories. But as far as I can remember, this vulnerability affects only privileged helper tools and mach services.

I believe that XPC services must be one-trick ponies that avoid installing any binaries with a root access. In such case macOS would take care of everything by default. For example, you can launch a XPC service only from the standard location.

As a result, you don’t want to manage an underlying audit token. Makes sense?

**Comment by jeff-h** [comment]
It's almost certain I am totally crossing a few wires here :) You're right, my current use-case and the examples given in the URLs above are all for privileged helpers. My confusion is because the helpers are communicating with their parent app via XPC, and at least one of the [proposed solutions](https://theevilbit.github.io/posts/secure_coding_privilegedhelpertools_part1/#fix-such-and-similar-issues) to the vulnerability is to add some checks into the `NSXPCListenerDelegate`'s `listener` function.

**Comment by shpakovski** [comment]
I’m not convinced that those checks are necessary, but let’s wait for the second part of the article 🙂
